GET http://localhost:3001/api/candidates

###

GET http://localhost:3001/api/candidate/1

###

DELETE http://localhost:3001/api/candidate/1

###

POST http://localhost:3001/api/candidate
Content-Type: application/json

{
    "first_name": "Ronald",
    "last_name": "Firbank",
    "industry_connected": 1
}