GET http://localhost:3001/api/candidates

###

GET http://localhost:3001/api/candidate/1

###

DELETE http://localhost:3001/api/candidate/1

###

POST http://localhost:3001/api/candidate
Content-Type: application/json

{
    "first_name": "Ronald",
    "last_name": "Firbank",
    "industry_connected": 1
}

###

GET http://localhost:3001/api/parties

###

GET http://localhost:3001/api/party/1

###

DELETE http://localhost:3001/api/party/1

###

PUT http://localhost:3001/api/candidate/1
Content-Type: application/json

{
    "party_id": 1
}

###

GET http://localhost:3001/api/voters

###

GET http://localhost:3001/api/voter/10

###

POST http://localhost:3001/api/localhost:3001/api/voter
Content-Type: application/json
{
    "first_name": "Amiko",
    "last_name": "Cascade",
    "email": "amiko@schoolofcss.edu"
}

###

PUT http://localhost:3001/api/voter/1
Content-Type: application/json

{
    "email": "amiko@schoolofcss.edu"
}

###

DELETE http://localhost:3001/api/voter/1

